version: '2.2'

services:

  workstation:
    image: jeffwen0105/ansible_server:0.3
    hostname: workstation      
    privileged: true
    command: ['/sbin/init']
    volumes:
      - mydata:/home/student/playground
    extra_hosts:
      - "workstation.lab.example.com:10.10.10.10"
      - "servera.lab.example.com:10.10.10.11"
      - "serverb.lab.example.com:10.10.10.12"
      - "serverc.lab.example.com:10.10.10.13"
      - "serverd.lab.example.com:10.10.10.14"
    networks:
      ansible:
        ipv4_address: 10.10.10.10   

  servera:
    image: jeffwen0105/ansible_server:0.3
    hostname: servera
    privileged: true
    command: ['/sbin/init']
    extra_hosts:
      - "workstation.lab.example.com:10.10.10.10"
      - "servera.lab.example.com:10.10.10.11"
      - "serverb.lab.example.com:10.10.10.12"
      - "serverc.lab.example.com:10.10.10.13"
      - "serverd.lab.example.com:10.10.10.14"
    networks:
      ansible:
        ipv4_address: 10.10.10.11    

  serverb:
    image: jeffwen0105/ansible_server:0.3
    hostname: serverb
    privileged: true
    command: ['/sbin/init']
    extra_hosts:
      - "workstation.lab.example.com:10.10.10.10"
      - "servera.lab.example.com:10.10.10.11"
      - "serverb.lab.example.com:10.10.10.12"
      - "serverc.lab.example.com:10.10.10.13"
      - "serverd.lab.example.com:10.10.10.14"
    networks:
      ansible:
        ipv4_address: 10.10.10.12    

  serverc:
    image: jeffwen0105/ansible_server:0.3
    hostname: serverc  
    privileged: true
    command: ['/sbin/init']
    extra_hosts:
      - "workstation.lab.example.com:10.10.10.10"
      - "servera.lab.example.com:10.10.10.11"
      - "serverb.lab.example.com:10.10.10.12"
      - "serverc.lab.example.com:10.10.10.13"
      - "serverd.lab.example.com:10.10.10.14"
    networks:
      ansible:
        ipv4_address: 10.10.10.13

  serverd:
    image: jeffwen0105/ansible_server:0.3
    hostname: serverd
    privileged: true
    command: ['/sbin/init']
    extra_hosts:
      - "workstation.lab.example.com:10.10.10.10"
      - "servera.lab.example.com:10.10.10.11"
      - "serverb.lab.example.com:10.10.10.12"
      - "serverc.lab.example.com:10.10.10.13"
      - "serverd.lab.example.com:10.10.10.14"
    networks:
      ansible:
        ipv4_address: 10.10.10.14

networks:
  ansible:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.10.10/16
          gateway: 10.10.10.1

volumes:
  mydata:
